// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaM_h1bLGn_CEiiopEaLN1uSpvySpiT3Q',
    appId: '1:134288487187:web:2511d3006a42839928a0e6',
    messagingSenderId: '134288487187',
    projectId: 'nyaay-flutter',
    authDomain: 'nyaay-flutter.firebaseapp.com',
    storageBucket: 'nyaay-flutter.appspot.com',
    measurementId: 'G-TDFZRYKDKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmDMTvFX2z9RQPuVqAMHzxjVIzFSGdP6s',
    appId: '1:134288487187:android:bfc49187dfed950728a0e6',
    messagingSenderId: '134288487187',
    projectId: 'nyaay-flutter',
    storageBucket: 'nyaay-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAYfiEUUtrVFV3WuwfEhJInpf8EkQmglM',
    appId: '1:134288487187:ios:79da43f31ad8510628a0e6',
    messagingSenderId: '134288487187',
    projectId: 'nyaay-flutter',
    storageBucket: 'nyaay-flutter.appspot.com',
    iosBundleId: 'com.example.nyaay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAYfiEUUtrVFV3WuwfEhJInpf8EkQmglM',
    appId: '1:134288487187:ios:79da43f31ad8510628a0e6',
    messagingSenderId: '134288487187',
    projectId: 'nyaay-flutter',
    storageBucket: 'nyaay-flutter.appspot.com',
    iosBundleId: 'com.example.nyaay',
  );
}
